name: CI Pull Request

on:
  pull_request:          # Kích hoạt khi có Pull Request
    branches: [ main ]   # PR vào nhánh main thì chạy

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Hoặc version bạn dùng

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest  # hoặc lệnh test của bạn
